//Bio Data
var myname = "Iqra Naz";
console.log("1) My name is ".concat(myname));
var fathername = "Muhammad asgar";
console.log("2) My father name is ".concat(fathername));
var age = 20;
console.log("3) My age is ".concat(age));
var marital_status = "single";
console.log("4) I am ".concat(marital_status));
var height = 5.6;
console.log("5) My height is ".concat(height));
var country = "Pakistan";
console.log("6) My country name is ".concat(country));
var city = "Karachi";
console.log("7) My city name is ".concat(city));
var muslim = true;
console.log("8) I am muslim ".concat(muslim));
var religion = "Islam";
console.log("9) My religion is ".concat(religion));
var educated = true;
console.log("10) I am educated ".concat(educated));
var education = "Intermediate of medical science";
console.log("11) My education is ".concat(education));
var dateofbirth = "12-02-2004";
console.log("12) I was born in ".concat(dateofbirth));
var hobbies = "Reading,painting,Eating,Travelling";
console.log("13) My hobbies is ".concat(hobbies));
var course = "Artificial Intelligence";
console.log("14) I am doing a ".concat(course, " course in Governor House"));
var goal = "web developer";
console.log("15) I want to become a proficient ".concat(goal));
var cast = "Sheikh";
console.log("16) My cast is ".concat(cast));
var favorite_colour = "Purple";
console.log("17) My favorite colour is ".concat(favorite_colour));
var favorite_animals = "Lion,Peacock,Giraffe";
console.log("18) My favorite animals is ".concat(favorite_animals));
var favorite_personality = "Quaid-e-Azam Muhammad Ali Jinnah";
console.log("19) My favorite personality is ".concat(favorite_personality));
var favorite_dish = "Biryani";
console.log("20) I like to eat ".concat(favorite_dish));
var favorite_game = "Bubble shooter";
console.log("21) My favorite game is ".concat(favorite_game));
var favorite_country = "Turkey";
console.log("22) My favorite country is ".concat(favorite_country));
var favorite_place = "Sea side";
console.log("23) My favorite place is ".concat(favorite_place));
var favorite_sports = "Racket,Cricket";
console.log("24) My favorite sports is ".concat(favorite_sports));
var wish = "Perform umrah with my parents";
console.log("25) I want to ".concat(wish));
var favorite_subject = "Biology";
console.log("26) My favorite subject is ".concat(favorite_subject));
var is_intelligent = true;
console.log("27) I am very intelligent ".concat(is_intelligent));
var is_beautifull = true;
console.log("28) I am beautifull ".concat(is_beautifull));
var matric_result = "89%";
matric_result = "Pass";
matric_result = "Aone";
console.log("29) My matric result is ".concat(matric_result, " grade with 89%"));
var intermediate_result = "80%";
intermediate_result = "Pass";
intermediate_result = "A";
console.log("30) My intermediate result is ".concat(intermediate_result, " grade with 80%"));
var favorite_nationalsong = "Dil Dill Pakistan";
favorite_nationalsong = "Shukriya Pakistan";
console.log("31) My favorite national song is ".concat(favorite_nationalsong));
var favorite_poet = "Allama Iqbal";
console.log("32) My favorite poet is ".concat(favorite_poet));
var favorite_cricketer = "Shahid Afridi";
favorite_cricketer = "Babar Azam";
console.log("33) My favorite cricketer is ".concat(favorite_cricketer));
var favorite_holybook = "Quran Majeed";
console.log("34) My favorite holy book is ".concat(favorite_holybook));
var interest = "Coding";
console.log("35) I am interested in ".concat(interest));
var favorite_seaside = "Neelum Valley";
console.log("36) My favorite seaside is ".concat(favorite_seaside));
var skill = "learning typescript";
console.log("37) I am currently ".concat(skill, " as a skill"));
var language = "Urdu";
language = "urdu speaking";
console.log("38) I am ".concat(language));
var nationality = "Pakistani";
console.log("39) I am ".concat(nationality));
var siblings = "1 sister and 1 brother";
console.log("40) I have ".concat(siblings));
var school_name = " Shaheen public english cambridge school";
console.log("41) My school name is ".concat(school_name));
var clg_name = "For women clg for nazimabad";
console.log("42) My clg name is ".concat(clg_name));
var favorite_teacher = "Miss Hira";
console.log("43) My favorite teacher is ".concat(favorite_teacher));
var gender = "Girl";
console.log("44) I am a ".concat(gender));
var truthspeaker = "I speak the truth";
console.log("45) ".concat(truthspeaker));
var happiness = "I am always happy";
console.log("46) ".concat(happiness));
//I m thankful for completing 150 lines of my bio data
var closingline = "Thank you for considering my bio data";
console.log("47) ".concat(closingline));
